refactor(seed)!: use randv2
BREAKING CHANGE: this yields different results for the same seeds.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -88,17 +88,19 @@ jobs:
   test:
     name: Matrix Test
     needs: build
-    runs-on: ubuntu-latest
-    timeout-minutes: 15
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 5
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
-        # list whatever Terraform versions here you would like to support
+        os:
+          - ubuntu-latest
+          - macos-latest
+          - windows-latest
         terraform:
-          - '1.0.5'
-          - '1.11.4'
           - '1.12.2'
           - '1.13.5'
+          - '1.14.3'
     steps:
 
     - name: Set up Go
@@ -115,18 +117,31 @@ jobs:
         go mod download
 
     - name: TF acceptance tests
+      shell: bash
       timeout-minutes: 10
       env:
         TF_ACC: "1"
         TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
-
-        # Set whatever additional acceptance test env vars here. You can
-        # optionally use data from your repository secrets using the
-        # following syntax:
-        # SOME_VAR: ${{ secrets.SOME_VAR }}
-
       run: |
-        go test -v -coverprofile=coverage.txt -covermode=atomic ./internal/provider/
+        go test -v -coverprofile=coverage.txt -covermode=atomic ./internal/provider/...
+
+
+    - name: TF warnings tests
+      timeout-minutes: 5
+      shell: bash
+      env:
+        TF_ACC: "1"
+        TF_LOG: "WARN"
+        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
+      run: |
+        output=$(TF_ACC=1 TF_LOG="WARN" go test -v -run ^TestAccNanoIDDataSource_DashInAlphabet$ ./internal/provider/ 2>&1)
+        if echo "$output" | grep -q "The alphabet contains '-'"; then
+            echo "✓ Warning correctly emitted"
+            exit 0
+        else
+            echo "✗ Expected warning not found"
+            exit 1
+        fi
 
     - name: Upload coverage reports to Codecov
       uses: codecov/codecov-action@v5
